//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetKlinik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHayvanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHayvanlar()
        {
            this.TblHastaSahipleri = new HashSet<TblHastaSahipleri>();
            this.TblMuayeneKayitlari = new HashSet<TblMuayeneKayitlari>();
        }
    
        public int HastaID { get; set; }
        public string HastaAdi { get; set; }
        public string Tur { get; set; }
        public string Cins { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public int SahipID { get; set; }
        public string CipNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHastaSahipleri> TblHastaSahipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMuayeneKayitlari> TblMuayeneKayitlari { get; set; }
        public virtual TblSahipler TblSahipler { get; set; }
    }
}
