//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetKlinik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHastaSahipleri
    {
        public int SahipID { get; set; }
        public int HastaID { get; set; }
        public string SahiplikTipi { get; set; }
    
        public virtual TblHayvanlar TblHayvanlar { get; set; }
        public virtual TblSahipler TblSahipler { get; set; }
    }
}
