//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetKlinik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIslemler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblIslemler()
        {
            this.TblMuayeneIslemleri = new HashSet<TblMuayeneIslemleri>();
        }
    
        public int IslemID { get; set; }
        public string IslemAdi { get; set; }
        public decimal BirimFiyat { get; set; }
        public Nullable<int> StokMiktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMuayeneIslemleri> TblMuayeneIslemleri { get; set; }
    }
}
