//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetKlinik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMuayeneIslemleri
    {
        public int MuayeneIslemID { get; set; }
        public int KayitID { get; set; }
        public int IslemID { get; set; }
    
        public virtual TblIslemler TblIslemler { get; set; }
        public virtual TblMuayeneKayitlari TblMuayeneKayitlari { get; set; }
    }
}
