//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetKlinik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMuayeneKayitlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMuayeneKayitlari()
        {
            this.TblMuayeneIslemleri = new HashSet<TblMuayeneIslemleri>();
        }
    
        public int KayitID { get; set; }
        public int HastaID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public string TeshisveNotlar { get; set; }
        public decimal Ucret { get; set; }
    
        public virtual TblHayvanlar TblHayvanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMuayeneIslemleri> TblMuayeneIslemleri { get; set; }
    }
}
