//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetKlinik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DVetKlinikEntities : DbContext
    {
        public DVetKlinikEntities()
            : base("name=DVetKlinikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblHastaSahipleri> TblHastaSahipleri { get; set; }
        public virtual DbSet<TblHayvanlar> TblHayvanlar { get; set; }
        public virtual DbSet<TblIslemler> TblIslemler { get; set; }
        public virtual DbSet<TblMuayeneKayitlari> TblMuayeneKayitlari { get; set; }
        public virtual DbSet<TblSahipler> TblSahipler { get; set; }
        public virtual DbSet<TblKullanicilar> TblKullanicilar { get; set; }
    }
}
